### ISSUE TITLE
Regression in rating.php

### ISSUE THREAD

**Issue by rohitchormale** [AGProjects/cdrtool#2]
When importing rates, if ops == "2", rates are gettings skipped. Looks like this is because of regression. When removing support for mongodb, ops "2", related code is also deleted. Attaching diff output for reference.

![regression](https://github.com/AGProjects/cdrtool/assets/3373460/101d22c9-befd-41b7-b574-95eac04fd79a)

Also I would like to take this opportunity to thank for the remarkable software. You guys are the best. Keep doing good job.

**Comment by tijmenNL** [comment]
Humm that could be. I will check it.

**Comment by rohitchormale** [comment]
ok great. Thanks for quick repsonse. It is working with new code.
